services:
  chemist-hub:
    container_name: chemist-hub
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      - CHEMIST_HUB_HOST
      - CHEMIST_HUB_PORT
    stdin_open: true
    tty: true
